# Generated by Django 4.2.1 on 2023-08-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_customeritemloan_status_customermoneyloan_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
