# Generated by Django 4.2.1 on 2023-08-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_itemloanpayment_moneyloanpayment_delete_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermoneyloan',
            name='iterest_accrued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
