# Generated by Django 4.2.1 on 2023-08-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_customermoneyloan_iterest_accrued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermoneyloan',
            old_name='iterest_accrued',
            new_name='interest_accrued',
        ),
    ]
