# Generated by Django 4.2.1 on 2023-08-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_gender'),
        ('debts', '0007_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeritemloan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemloans', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='customermoneyloan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneyloans', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='itemborrowed',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsborrowed', to='users.customer'),
        ),
    ]
