# Generated by Django 4.2.1 on 2023-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0008_alter_customeritemloan_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='disburse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeritemloan',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=255),
        ),
    ]
