# Generated by Django 4.2.1 on 2023-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0009_loanapplication_disburse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermoneyloan',
            name='expected_repay_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customermoneyloan',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Defaulted', 'Defaulted'), ('Paying', 'Paying'), ('Reviewing', 'Reviewing')], default='Paying', max_length=255),
        ),
    ]
