# Generated by Django 4.2.1 on 2023-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0011_customeritemloan_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeritemloan',
            name='month',
        ),
        migrations.RemoveField(
            model_name='customeritemloan',
            name='year',
        ),
        migrations.AddField(
            model_name='itemborrowed',
            name='month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemborrowed',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
