# Generated by Django 4.2.4 on 2023-08-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Pieces', 'Pieces'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons'), ('Metres', 'Metres')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
