# Generated by Django 4.2.4 on 2023-08-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inventory_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
