# Generated by Django 4.2.4 on 2023-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inventory_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='brand',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Pieces', 'Pieces'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons'), ('Metres', 'Metres'), ('Litres', 'Litres')], max_length=255),
        ),
    ]
