# Generated by Django 4.1.7 on 2023-09-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_inventory_brand_alter_inventory_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="installment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="inventory",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
