# Generated by Django 4.1.7 on 2023-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lipalater", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lipalaterloan",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lipalaterloan",
            name="expected_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
